### ISSUE TITLE
Method wishlist

### ISSUE THREAD

**Issue by merkys** [ambs/Math-Matrix-MaybeGSL#3]
I started using `Math::Matrix::MaybeGSL` in my applications and here is the list of some methods I would like to see added:

- [ ] `transpose`
- [ ] `sum` (sum of two equidimensional matrices)
- [x] `row` (returns a new matrix consisting of a selected row)
- [ ] `rows` (returns a new matrix consisting of selected rows)

Would you be willing to accept PRs implementing these methods?

**Comment by ambs** [comment]
Dear @merkys, I am currently not using this module, thus my time is limited to develop new features. Nevertheless, I am more than happy to accept PRs and releasing new versions.

**Comment by merkys** [comment]
Thanks a lot @ambs, I will open PRs then.
